# Generated by Django 3.0.2 on 2020-01-16 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
